# Font
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.5

# Cursor
# block beam underline
cursor_shape underline
# cursor_beam_thickness 1.0
# cursor_underline_thickness 1.0
cursor_blink_interval 1.0
cursor_stop_blinking_after 8.0
cursor_trail 1
# cursor_trail_color none
# cursor_trail_decay 0.1 0.4
# cursor_trail_start_threshold 2

# Scrollbar
scrollbar scrolled
scrollbar_interactive yes

# Mouse
mouse_hide_wait -1.0
show_hyperlink_targets yes
underline_hyperlinks hover

# Window
window_margin_width 10
window_logo_path ~/dotfiles/kitty/images/lucario_mega.png
window_logo_position top-right
window_logo_alpha 1
window_logo_scale 15
confirm_os_window_close 0

# Color Scheme
background_opacity 0.3
# background_image ~/dotfiles/kitty/images/lucario_mega.png
# background_image_layout
# background_image_linear
# background_tint
# background_tint_gaps
