# Font
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.5

# Cursor
# block beam underline
cursor_shape underline
# cursor_beam_thickness 1.0
# cursor_underline_thickness 1.0
cursor_blink_interval 1.0
cursor_stop_blinking_after 8.0
cursor_trail 5
# cursor_trail_color none
# cursor_trail_decay 0.1 0.4
# cursor_trail_start_threshold 2

# Window
window_padding_width 10

# Border
# inactive_border_color       #2c313c
# active_border_color         #2c313c
# bell_border_color           #e06c75

# Opacity Config
background_opacity 0.3
dinamic_background_opacity yes

# Comportamiento
mouse_hide_wait -1.0
detect_urls yes
confirm_os_window_close 0 # Evitar confirmacion para cerrar terminal
