"$schema" = 'https://starship.rs/config-schema.json'

palette= "tokyonight"

format = """
[░▒▓](#a3aed2)\
[ 󰣇 ](bg:logo fg:black)\
[](fg:logo bg:dir)\
$directory\
[](fg:dir bg:git)\
$git_branch\
$git_state\
[](fg:git bg:module)\
$rust\
[](fg:module bg:clock)\
$time\
[ ](fg:clock)\
$cmd_duration\
\n$character"""

[directory]
style = "fg:white bg:dir"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Downloads" = " "
"dotfiles" = "👻"    # 🏗️ ⚙️ 🚧
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:git"
format = '[[ $symbol $branch ](fg:dir bg:git)]($style)'

[git_status]
style = "bg:git"
format = '[[($all_status$ahead_behind )](fg:dir bg:git)]($style)'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[🍒 PICKING](bold red)'
rebase = '[🏗️ REBASING](bold yellow)'
merge = '[🧬 MERGING](bold blue)'
bisect = '[🕵️ BISECTING](bold cyan)'
revert = '[🚑 REVERTING](bold bright-red)'

[rust]
symbol = "🦀"  # 
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:dir bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:mauve bg:clock)]($style)'

[cmd_duration]
min_time = 2_000
show_milliseconds = false

[palettes.tokyonight]
black = "#090c0c"
white = "#e3e5e5"
mauve = "#a0a9cb"

logo = "#a3aed2"
dir = "#769ff0"
git = "#394260"
module = "#212736"
clock = "#1d2230"
