general {
    lock_cmd = pidof hyprlock || hyprlock	# definimos el metodo de bloqueo
    # Hypridle, en general el ecosistema entero no escucha el D-bus, sino los mensajes del protocolo Hyprland-lock-notify
    # Una vez Hyprland detecta que la pantalla esta segura (cuando hyprlock consigue el bloqueo grafico), avisa pero Hypridle no responde a la solicitud de lock del D-bus y por eso se hara en esta linea para que el estado de LockedHint cambie a yes si hyprlock tiene exito
    on_lock_cmd = busctl call org.freedesktop.login1 /org/freedesktop/login1/session/auto org.freedesktop.login1.Session SetLockedHint b true
    on_unlock_cmd = busctl call org.freedesktop.login1 /org/freedesktop/login1/session/auto org.freedesktop.login1.Session SetLockedHint b false
    # Tambien hay que informar del desbloqueo

    before_sleep_cmd = loginctl lock-session	# lock before suspend # importante para que si algo duerme al sistema se bloquee, en caso contrario se despertaria desnudo (sin bloqueo) # se usa aqui el loginctl para que todo el sistema se entere de que está lockeado
    after_sleep_cmd = hyprctl dispatch dpms on	# to avoid having to press a key twice to turn on the display # despierta sistemas que no se enteran del estado de la sesion, por ejemplo, a veces la pantalla que se queda apagada o las luces de perifericos
}

# Avisar de inactividad
listener {
    timeout = 240
    on-timeout = brightnessctl -s set 70%
    on-resume = brightnessctl -r
}

# Activar pantalla de bloqueo # Tras el timeout en 1 min se suspendera por el siguiente listener
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Apagar pantalla cuando la sesion esta lockeada
listener {
    timeout = 60
    # abstraccion con loginctl
    on-timeout = loginctl show-session $XDG_SESSION_ID -p LockedHint --value | grep -q yes && hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on # hace falta porque si el sistema no se ha dormido after_sleep_cmd no se ejecuta
}

# Suspender Sistema
listener {
    timeout = 1200
    on-timeout = systemctl suspend
}
