general {
    lock_cmd = pidof hyprlock || hyprlock	# definimos el metodo de bloqueo
    # unlock_cmd =   # default	# no se aconseja añadir logintctl unlock-session pues el proceso de desbloqueo se realiza de modo automatico # Una vez la clave es introducida correctamente en hyprlock y PAM la valida, ya es hyprlock quien avisa al sistema de que marque la sesion como activa # se usa para definir el comportamiento al recibir una señal de desbloqueo del d-bus
    on_unlock_cmd =  # se usa para definir un comportamiento una vez la sesion se desbloquea
    before_sleep_cmd = loginctl lock-session	# lock before suspend # importante para que si algo duerme al sistema se bloquee, en caso contrario se despertaria desnudo (sin bloqueo) # se usa aqui el loginctl para que todo el sistema se entere de que está lockeado
    after_sleep_cmd = hyprctl dispatch dpms on	# to avoid having to press a key twice to turn on the display # despierta sistemas que no se enteran del estado de la sesion, por ejemplo, a veces la pantalla que se queda apagada o las luces de perifericos
}

# Avisar de inactividad
listener {
    timeout = 240
    on-timeout = brightnessctl -s set 70%
    on-resume = brightnessctl -r
}

# Activar pantalla de bloqueo
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Apagar pantalla
listener {
    timeout = 500
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on # hace falta porque si el sistema no se ha dormido after_sleep_cmd no se ejecuta
}

# Suspender Sistema
listener {
    timeout = 1200
    on-timeout = systemctl suspend
}
