preload = ~/dotfiles/hypr/backgrounds/walls/dragon.jpg

wallpaper {
    monitor =
    path = ~/dotfiles/hypr/backgrounds/walls/dragon.jpg
    fit_mode = cover # default
    # timeout = 30 # default # timeout between each wallpaper change if path is a directory
    # order = random # default
}

# misc options are set to default
